param([Parameter(Mandatory=$true)][string]$InstallRoot,[Parameter(Mandatory=$true)][string]$DataRoot)
$ErrorActionPreference='Stop';$fail=New-Object Collections.Generic.List[string];$roles=@(@{role='core';service='SistemaImuneCore'},@{role='vault';service='SistemaImuneVault'},@{role='policy';service='SistemaImunePolicy'},@{role='execution';service='SistemaImuneExecution'},@{role='gateway';service='SistemaImuneGateway'},@{role='provider';service='SistemaImuneProvider'},@{role='adapter';service='SistemaImuneAdapter'},@{role='watchdog';service='SistemaImuneWatchdog'})
try{$lock=Get-Content (Join-Path $InstallRoot 'release-lock.txt') -Raw;if($lock-notmatch'CORE_TAG=v1\.1\.1'){$fail.Add('CORE_TAG_MISMATCH')};if($lock-notmatch'CORE_COMMIT=d4750b24336d9b88663473d2db32a796e419e46f'){$fail.Add('CORE_COMMIT_MISMATCH')}}catch{$fail.Add('RELEASE_LOCK_MISSING')}
try{foreach($line in Get-Content (Join-Path $InstallRoot 'payload.sha256')){if([string]::IsNullOrWhiteSpace($line)){continue};$exp=$line.Substring(0,64);$rel=$line.Substring(66).Replace('/','\');$p=Join-Path $InstallRoot $rel;if(-not(Test-Path $p)){$fail.Add("PAYLOAD_MISSING:$rel");continue};if((Get-FileHash $p -Algorithm SHA256).Hash.ToLowerInvariant()-ne$exp.ToLowerInvariant()){$fail.Add("PAYLOAD_HASH:$rel")}}}catch{$fail.Add('PAYLOAD_INTEGRITY_EXCEPTION')}
$sec=$null;try{$sec=Get-Content (Join-Path $DataRoot 'host-security.json') -Raw|ConvertFrom-Json}catch{$fail.Add('HOST_SECURITY_MISSING')};if($sec-and[bool]$sec.root_attested){& (Join-Path $InstallRoot 'host\verify-root.ps1') -InstallRoot $InstallRoot -DataRoot $DataRoot -Quiet;if($LASTEXITCODE-ne0){$fail.Add('HARDWARE_ROOT_VERIFY_FAILED')}}
try{$c=Get-Content (Join-Path $DataRoot 'system-contract.json') -Raw|ConvertFrom-Json;if([int]$c.protected_systems-ne0){$fail.Add('PROTECTED_SYSTEM_COUNT_INVALID')};if([string]$c.state-notin@('UNATTACHED','PENDING_HOMOLOGATION','DISCOVERY_BLOCKED','OPERATIONAL')){$fail.Add('CONTRACT_STATE_INVALID')}}catch{$fail.Add('SYSTEM_CONTRACT_MISSING')}
$deadline=(Get-Date).AddSeconds(30);do{$m=@();foreach($x in $roles){if(-not(Test-Path (Join-Path $DataRoot ("roles\$($x.role)\heartbeat.json")))){$m+=$x.role}};if($m.Count-eq0){break};Start-Sleep 1}while((Get-Date)-lt$deadline)
foreach($x in $roles){$s=Get-Service $x.service -ErrorAction SilentlyContinue;if(-not$s){$fail.Add("SERVICE_MISSING:$($x.service)");continue};if($s.Status-ne'Running'){$fail.Add("SERVICE_NOT_RUNNING:$($x.service):$($s.Status)")};$hb=Join-Path $DataRoot ("roles\$($x.role)\heartbeat.json");if(-not(Test-Path $hb)){$fail.Add("HEARTBEAT_MISSING:$($x.role)")}}
foreach($svc in @('SistemaImuneCore','SistemaImuneVault','SistemaImunePolicy','SistemaImuneExecution','SistemaImuneAdapter','SistemaImuneWatchdog')){$rn="Sistema Imunologico - deny outbound - $svc";$fw=Get-NetFirewallRule -DisplayName $rn -ErrorAction SilentlyContinue;if(-not$fw){$fail.Add("FIREWALL_RULE_MISSING:$svc")}}
if($fail.Count-eq0){'INSTALLER_SELF_TEST=PASS';'CORE_RELEASE=v1.1.1';'CORE_COMMIT=d4750b24336d9b88663473d2db32a796e419e46f';"ROOT_ATTESTED=$([bool]$sec.root_attested)";"SECURE_BOOT=$([bool]$sec.secure_boot)";"TPM_PRESENT=$([bool]$sec.tpm_present)";"TPM_READY=$([bool]$sec.tpm_ready)";'SERVICE_COUNT=8';'MODE=CONTAINED_READ_ONLY';'PROTECTED_SYSTEMS=0';exit 0};'INSTALLER_SELF_TEST=FAIL';$fail|%{"FAIL=$_"};exit 10
